<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MembersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        // Assure-toi d'avoir déjà des guildes et des pouvoirs créés pour ces ID
        DB::table('members')->insert([
            // OnTheTop Member
            ['ingame_name' => 'Dreamak_', 'guilds_id' => 1, 'powers_id' => 1],
            ['ingame_name' => 'Opiumz', 'guilds_id' => 1, 'powers_id' => 2],
            ['ingame_name' => 'JiiBi', 'guilds_id' => 1, 'powers_id' => 3],
            ['ingame_name' => 'Yurusenzo', 'guilds_id' => 1, 'powers_id' => 4],
            ['ingame_name' => 'Lameduse', 'guilds_id' => 1, 'powers_id' => 5],
            ['ingame_name' => 'Lylith', 'guilds_id' => 1, 'powers_id' => 6],
            ['ingame_name' => 'Owenyob', 'guilds_id' => 1, 'powers_id' => 7],
            ['ingame_name' => 'jjyu', 'guilds_id' => 1, 'powers_id' => 8],
            ['ingame_name' => 'DamsCQT', 'guilds_id' => 1, 'powers_id' => 9],
            ['ingame_name' => 'Illusion', 'guilds_id' => 1, 'powers_id' => 10],
            ['ingame_name' => 'Panda', 'guilds_id' => 1, 'powers_id' => 11],
            ['ingame_name' => 'Vehen', 'guilds_id' => 1, 'powers_id' => 12],
            ['ingame_name' => 'Crackead', 'guilds_id' => 1, 'powers_id' => 13],
            ['ingame_name' => 'Lali', 'guilds_id' => 1, 'powers_id' => 14],
            ['ingame_name' => 'Gutz', 'guilds_id' => 1, 'powers_id' => 15],
            ['ingame_name' => 'Kaiez', 'guilds_id' => 1, 'powers_id' => 16],
            ['ingame_name' => 'Sportex', 'guilds_id' => 1, 'powers_id' => 17],
            ['ingame_name' => 'Venkyu', 'guilds_id' => 1, 'powers_id' => 18],
            ['ingame_name' => 'Maelhinio', 'guilds_id' => 1, 'powers_id' => 19],
            ['ingame_name' => 'Riley', 'guilds_id' => 1, 'powers_id' => 20],
            ['ingame_name' => 'Nooum', 'guilds_id' => 1, 'powers_id' => 21],
            ['ingame_name' => 'HeavenI420', 'guilds_id' => 1, 'powers_id' => 22],
            ['ingame_name' => 'IBenYnutSI', 'guilds_id' => 1, 'powers_id' => 23],
            ['ingame_name' => 'Miioh', 'guilds_id' => 1, 'powers_id' => 24],
            ['ingame_name' => 'LeGrandMage', 'guilds_id' => 1, 'powers_id' => 25],
            ['ingame_name' => 'MnMs', 'guilds_id' => 1, 'powers_id' => 26],
            ['ingame_name' => 'Snow', 'guilds_id' => 1, 'powers_id' => 27],
            ['ingame_name' => 'Sting', 'guilds_id' => 1, 'powers_id' => 28],
            ['ingame_name' => 'Dirzton', 'guilds_id' => 1, 'powers_id' => 29],
            ['ingame_name' => 'Trameon', 'guilds_id' => 1, 'powers_id' => 30],
            ['ingame_name' => 'Ulmeo', 'guilds_id' => 1, 'powers_id' => 31],
            ['ingame_name' => 'PrinceArt', 'guilds_id' => 1, 'powers_id' => 32],
            ['ingame_name' => 'Senaytt', 'guilds_id' => 1, 'powers_id' => 33],
            ['ingame_name' => 'Fay', 'guilds_id' => 1, 'powers_id' => 34],
            ['ingame_name' => 'desmo', 'guilds_id' => 1, 'powers_id' => 35],
            ['ingame_name' => 'Lanmart', 'guilds_id' => 1, 'powers_id' => 36],
            ['ingame_name' => 'NoixDeCoco', 'guilds_id' => 1, 'powers_id' => 37],
            ['ingame_name' => 'Nailex', 'guilds_id' => 1, 'powers_id' => 38],
            ['ingame_name' => 'Jordan', 'guilds_id' => 1, 'powers_id' => 39],
            ['ingame_name' => 'JusDFruit', 'guilds_id' => 1, 'powers_id' => 40],
            ['ingame_name' => 'TheRizzen', 'guilds_id' => 1, 'powers_id' => 41],
            ['ingame_name' => 'TonPère', 'guilds_id' => 1, 'powers_id' => 42],
            ['ingame_name' => 'Akihito_', 'guilds_id' => 1, 'powers_id' => 43],
            ['ingame_name' => 'r2eno77', 'guilds_id' => 1, 'powers_id' => 44],
            ['ingame_name' => 'ZuntyhK', 'guilds_id' => 1, 'powers_id' => 45],
            ['ingame_name' => 'PainCroquant', 'guilds_id' => 1, 'powers_id' => 46],
            ['ingame_name' => 'JusteMarlotte', 'guilds_id' => 1, 'powers_id' => 47],
            ['ingame_name' => 'SprinteurFou', 'guilds_id' => 1, 'powers_id' => 48],
            ['ingame_name' => 'Baozi', 'guilds_id' => 1, 'powers_id' => 49],
            ['ingame_name' => 'random', 'guilds_id' => 1, 'powers_id' => 50],
            ['ingame_name' => 'Prince', 'guilds_id' => 1, 'powers_id' => 51],
            ['ingame_name' => 'Towaruu', 'guilds_id' => 1, 'powers_id' => 52],
            ['ingame_name' => 'Nico78', 'guilds_id' => 1, 'powers_id' => 53],
            ['ingame_name' => 'Brennus', 'guilds_id' => 1, 'powers_id' => 54],
            ['ingame_name' => 'Kynn_', 'guilds_id' => 1, 'powers_id' => 55],
            ['ingame_name' => 'Beabwoo', 'guilds_id' => 1, 'powers_id' => 56],
            ['ingame_name' => 'Fruitduchene', 'guilds_id' => 1, 'powers_id' => 57],
            ['ingame_name' => 'Matex', 'guilds_id' => 1, 'powers_id' => 58],
            ['ingame_name' => 'Tralknor', 'guilds_id' => 1, 'powers_id' => 59],
            ['ingame_name' => 'Esteban21', 'guilds_id' => 1, 'powers_id' => 60],
            ['ingame_name' => 'Swangel', 'guilds_id' => 1, 'powers_id' => 61],
            ['ingame_name' => 'Tabz76', 'guilds_id' => 1, 'powers_id' => 62],
            ['ingame_name' => 'PoketMan', 'guilds_id' => 1, 'powers_id' => 63],
            ['ingame_name' => 'Enjoy2K', 'guilds_id' => 1, 'powers_id' => 64],
            ['ingame_name' => 'Chpyls', 'guilds_id' => 1, 'powers_id' => 65],
            ['ingame_name' => 'Adamas', 'guilds_id' => 1, 'powers_id' => 66],
            ['ingame_name' => 'KaraBuu', 'guilds_id' => 1, 'powers_id' => 67],
            ['ingame_name' => 'Raz5000', 'guilds_id' => 1, 'powers_id' => 68],
            ['ingame_name' => 'MATTZOMBIMAN', 'guilds_id' => 1, 'powers_id' => 69],
            ['ingame_name' => 'Ricardo', 'guilds_id' => 1, 'powers_id' => 70],
            ['ingame_name' => 'Marie113', 'guilds_id' => 1, 'powers_id' => 71],
            ['ingame_name' => 'Albator', 'guilds_id' => 1, 'powers_id' => 72],
            ['ingame_name' => 'Dartack', 'guilds_id' => 1, 'powers_id' => 73],
            ['ingame_name' => 'ldr4g', 'guilds_id' => 1, 'powers_id' => 74],
            ['ingame_name' => 'xirn', 'guilds_id' => 1, 'powers_id' => 75],
            ['ingame_name' => 'Nana', 'guilds_id' => 1, 'powers_id' => 76],
            ['ingame_name' => 'Weasel', 'guilds_id' => 1, 'powers_id' => 77],
            ['ingame_name' => 'lokiko', 'guilds_id' => 1, 'powers_id' => 78],
            ['ingame_name' => 'Eliott', 'guilds_id' => 1, 'powers_id' => 79],
            ['ingame_name' => 'KaiKai', 'guilds_id' => 1, 'powers_id' => 80],
            ['ingame_name' => 'Tanukiller', 'guilds_id' => 1, 'powers_id' => 81],
            ['ingame_name' => 'RoiSaanaa', 'guilds_id' => 1, 'powers_id' => 82],
            // TheLastHope Member
            ['ingame_name'  => 'Havana23', 'guilds_id' => 2, 'powers_id' => 83],
            ['ingame_name'  => 'Joker', 'guilds_id' => 2, 'powers_id' => 84],
            ['ingame_name'  => 'Sharkyo', 'guilds_id' => 2, 'powers_id' => 85],
            ['ingame_name'  => 'charllo', 'guilds_id' => 2, 'powers_id' => 86],
            ['ingame_name'  => 'Ethan2011', 'guilds_id' => 2, 'powers_id' => 87],
            ['ingame_name'  => 'Alfred', 'guilds_id' => 2, 'powers_id' => 88],
            ['ingame_name'  => 'Atriox', 'guilds_id' => 2, 'powers_id' => 89],
            ['ingame_name'  => 'Catwoman', 'guilds_id' => 2, 'powers_id' => 90],
            ['ingame_name'  => 'StraGher', 'guilds_id' => 2, 'powers_id' => 91],
            ['ingame_name'  => 'Mixture', 'guilds_id' => 2, 'powers_id' => 92],
            ['ingame_name'  => 'Slyde', 'guilds_id' => 2, 'powers_id' => 93],
            ['ingame_name'  => 'Lydou', 'guilds_id' => 2, 'powers_id' => 94],
            ['ingame_name'  => 'Bigpurple', 'guilds_id' => 2, 'powers_id' => 95],
            ['ingame_name'  => 'Tanjiro', 'guilds_id' => 2, 'powers_id' => 96],
            ['ingame_name'  => 'Sombri', 'guilds_id' => 2, 'powers_id' => 97],
            ['ingame_name'  => 'ZorUwU', 'guilds_id' => 2, 'powers_id' => 98],
            ['ingame_name'  => 'Neckso', 'guilds_id' => 2, 'powers_id' => 99],
            ['ingame_name'  => 'Krali', 'guilds_id' => 2, 'powers_id' => 100],
            ['ingame_name'  => 'SeriousChap', 'guilds_id' => 2, 'powers_id' => 101],
            ['ingame_name'  => 'TheFlash', 'guilds_id' => 2, 'powers_id' => 102],
            ['ingame_name'  => 'HarleyQueen', 'guilds_id' => 2, 'powers_id' => 103],
            ['ingame_name'  => 'Skyd3rz', 'guilds_id' => 2, 'powers_id' => 104],
            ['ingame_name'  => 'Tangcrz', 'guilds_id' => 2, 'powers_id' => 105],
            ['ingame_name'  => 'Shawn', 'guilds_id' => 2, 'powers_id' => 106],
            ['ingame_name'  => 'Miji', 'guilds_id' => 2, 'powers_id' => 107],
            ['ingame_name'  => 'Meli', 'guilds_id' => 2, 'powers_id' => 108],
            ['ingame_name'  => 'ShawdowOutSider', 'guilds_id' => 2, 'powers_id' => 109],
            ['ingame_name'  => 'Gordache', 'guilds_id' => 2, 'powers_id' => 110],
            ['ingame_name'  => 'ZekoO', 'guilds_id' => 2, 'powers_id' => 111],
            ['ingame_name'  => 'TomateMolle', 'guilds_id' => 2, 'powers_id' => 112],
            ['ingame_name'  => 'Elana', 'guilds_id' => 2, 'powers_id' => 113],
            ['ingame_name'  => 'Flo', 'guilds_id' => 2, 'powers_id' => 114],
            ['ingame_name'  => 'Kality', 'guilds_id' => 2, 'powers_id' => 115],
            ['ingame_name'  => 'Akametrique', 'guilds_id' => 2, 'powers_id' => 116],
            ['ingame_name'  => 'Mish0u', 'guilds_id' => 2, 'powers_id' => 117],
            ['ingame_name'  => 'Feenza', 'guilds_id' => 2, 'powers_id' => 118],
            ['ingame_name'  => 'Olbeback', 'guilds_id' => 2, 'powers_id' => 119],
            ['ingame_name'  => 'Solink', 'guilds_id' => 2, 'powers_id' => 120],
            ['ingame_name'  => 'Kairyu', 'guilds_id' => 2, 'powers_id' => 121],
            ['ingame_name'  => 'Schen', 'guilds_id' => 2, 'powers_id' => 122],
            ['ingame_name'  => 'Renox', 'guilds_id' => 2, 'powers_id' => 123],
            ['ingame_name'  => 'Heretik', 'guilds_id' => 2, 'powers_id' => 124],
            ['ingame_name'  => 'Guiguiggs', 'guilds_id' => 2, 'powers_id' => 125],
            ['ingame_name'  => 'swinder', 'guilds_id' => 2, 'powers_id' => 126],
            ['ingame_name'  => 'benjamin', 'guilds_id' => 2, 'powers_id' => 127],
            ['ingame_name'  => 'Nezzeur', 'guilds_id' => 2, 'powers_id' => 128],
            ['ingame_name'  => 'ZHANTO', 'guilds_id' => 2, 'powers_id' => 129],
            ['ingame_name'  => 'MelioD', 'guilds_id' => 2, 'powers_id' => 130],
            ['ingame_name'  => 'Batman', 'guilds_id' => 2, 'powers_id' => 131],
            ['ingame_name'  => 'Avare', 'guilds_id' => 2, 'powers_id' => 132],
            ['ingame_name'  => 'Aqxrr0', 'guilds_id' => 2, 'powers_id' => 133],
            ['ingame_name'  => 'Nemesiswolf', 'guilds_id' => 2, 'powers_id' => 134],
            ['ingame_name'  => 'Kiliangg', 'guilds_id' => 2, 'powers_id' => 135],
            ['ingame_name'  => 'Moonseeke', 'guilds_id' => 2, 'powers_id' => 136],
            ['ingame_name'  => 'Alexfr2', 'guilds_id' => 2, 'powers_id' => 137],
            ['ingame_name'  => 'cris', 'guilds_id' => 2, 'powers_id' => 138],
            ['ingame_name'  => 'Fabien', 'guilds_id' => 2, 'powers_id' => 139],
            ['ingame_name'  => 'Gazorp', 'guilds_id' => 2, 'powers_id' => 140],
            ['ingame_name'  => 'Psyco', 'guilds_id' => 2, 'powers_id' => 141],
            ['ingame_name'  => 'TheMerix', 'guilds_id' => 2, 'powers_id' => 142],
            ['ingame_name'  => 'LeC1NQ', 'guilds_id' => 2, 'powers_id' => 143],
            ['ingame_name'  => 'Dolazo', 'guilds_id' => 2, 'powers_id' => 144],
            ['ingame_name'  => 'WazaB', 'guilds_id' => 2, 'powers_id' => 145],
            ['ingame_name'  => 'Lurok', 'guilds_id' => 2, 'powers_id' => 146],
            ['ingame_name'  => 'younesdelast', 'guilds_id' => 2, 'powers_id' => 147],
            ['ingame_name'  => 'Youneedme', 'guilds_id' => 2, 'powers_id' => 148],
            ['ingame_name'  => 'Maac', 'guilds_id' => 2, 'powers_id' => 149],
            ['ingame_name'  => 'Kordyceps', 'guilds_id' => 2, 'powers_id' => 150],
            ['ingame_name'  => 'Thoto', 'guilds_id' => 2, 'powers_id' => 151],
            ['ingame_name'  => 'ZioxZordre', 'guilds_id' => 2, 'powers_id' => 152],
            ['ingame_name'  => 'Wizybrut', 'guilds_id' => 2, 'powers_id' => 153],
            ['ingame_name'  => 'Archansis', 'guilds_id' => 2, 'powers_id' => 154],
            ['ingame_name'  => 'GROUGA', 'guilds_id' => 2, 'powers_id' => 155],
            ['ingame_name'  => 'Nnanek', 'guilds_id' => 2, 'powers_id' => 156],
            ['ingame_name'  => 'Feunneck', 'guilds_id' => 2, 'powers_id' => 157],
            ['ingame_name'  => 'Antorse', 'guilds_id' => 2, 'powers_id' => 158],
            ['ingame_name'  => 'Feedecoeur', 'guilds_id' => 2, 'powers_id' => 159],
            ['ingame_name'  => 'Tigroulemal', 'guilds_id' => 2, 'powers_id' => 160],
        ]);
    }
}
