<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class PowersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        DB::table('powers')->insert([
            // OnTheTop Member power
            ['power' => '31905', 'date' => now()],
            ['power' => '33951', 'date' => now()],
            ['power' => '34742', 'date' => now()],
            ['power' => '33976', 'date' => now()],
            ['power' => '31016', 'date' => now()],
            ['power' => '30495', 'date' => now()],
            ['power' => '25566', 'date' => now()],
            ['power' => '28812', 'date' => now()],
            ['power' => '28115', 'date' => now()],
            ['power' => '26353', 'date' => now()],
            ['power' => '28669', 'date' => now()],
            ['power' => '29536', 'date' => now()],
            ['power' => '26374', 'date' => now()],
            ['power' => '26193', 'date' => now()],
            ['power' => '25872', 'date' => now()],
            ['power' => '25813', 'date' => now()],
            ['power' => '26390', 'date' => now()],
            ['power' => '27247', 'date' => now()],
            ['power' => '26234', 'date' => now()],
            ['power' => '24883', 'date' => now()],
            ['power' => '26803', 'date' => now()],
            ['power' => '24514', 'date' => now()],
            ['power' => '25537', 'date' => now()],
            ['power' => '25216', 'date' => now()],
            ['power' => '24588', 'date' => now()],
            ['power' => '23357', 'date' => now()],
            ['power' => '25837', 'date' => now()],
            ['power' => '22767', 'date' => now()],
            ['power' => '24197', 'date' => now()],
            ['power' => '24406', 'date' => now()],
            ['power' => '25287', 'date' => now()],
            ['power' => '22770', 'date' => now()],
            ['power' => '21369', 'date' => now()],
            ['power' => '23289', 'date' => now()],
            ['power' => '23868', 'date' => now()],
            ['power' => '23203', 'date' => now()],
            ['power' => '23480', 'date' => now()],
            ['power' => '21039', 'date' => now()],
            ['power' => '24095', 'date' => now()],
            ['power' => '22631', 'date' => now()],
            ['power' => '23589', 'date' => now()],
            ['power' => '22870', 'date' => now()],
            ['power' => '22181', 'date' => now()],
            ['power' => '23384', 'date' => now()],
            ['power' => '25089', 'date' => now()],
            ['power' => '20261', 'date' => now()],
            ['power' => '22133', 'date' => now()],
            ['power' => '20158', 'date' => now()],
            ['power' => '20904', 'date' => now()],
            ['power' => '22459', 'date' => now()],
            ['power' => '20532', 'date' => now()],
            ['power' => '20411', 'date' => now()],
            ['power' => '21929', 'date' => now()],
            ['power' => '22548', 'date' => now()],
            ['power' => '22103', 'date' => now()],
            ['power' => '21498', 'date' => now()],
            ['power' => '20740', 'date' => now()],
            ['power' => '19734', 'date' => now()],
            ['power' => '21630', 'date' => now()],
            ['power' => '22044', 'date' => now()],
            ['power' => '21241', 'date' => now()],
            ['power' => '22940', 'date' => now()],
            ['power' => '20797', 'date' => now()],
            ['power' => '23642', 'date' => now()],
            ['power' => '19366', 'date' => now()],
            ['power' => '20352', 'date' => now()],
            ['power' => '20030', 'date' => now()],
            ['power' => '21965', 'date' => now()],
            ['power' => '21119', 'date' => now()],
            ['power' => '21542', 'date' => now()],
            ['power' => '18951', 'date' => now()],
            ['power' => '21707', 'date' => now()],
            ['power' => '21232', 'date' => now()],
            ['power' => '20904', 'date' => now()],
            ['power' => '19370', 'date' => now()],
            ['power' => '20209', 'date' => now()],
            ['power' => '19509', 'date' => now()],
            ['power' => '18991', 'date' => now()],
            ['power' => '18870', 'date' => now()],
            ['power' => '18104', 'date' => now()],
            ['power' => '18726', 'date' => now()],
            ['power' => '19155', 'date' => now()],
            // TheLastHope Member power
            ['power' => '23440', 'date' => now()],
            ['power' => '26518', 'date' => now()],
            ['power' => '22888', 'date' => now()],
            ['power' => '28120', 'date' => now()],
            ['power' => '38570', 'date' => now()],
            ['power' => '27594', 'date' => now()],
            ['power' => '21029', 'date' => now()],
            ['power' => '19979', 'date' => now()],
            ['power' => '27443', 'date' => now()],
            ['power' => '21198', 'date' => now()],
            ['power' => '20194', 'date' => now()],
            ['power' => '21018', 'date' => now()],
            ['power' => '25038', 'date' => now()],
            ['power' => '19713', 'date' => now()],
            ['power' => '18252', 'date' => now()],
            ['power' => '23890', 'date' => now()],
            ['power' => '26994', 'date' => now()],
            ['power' => '23659', 'date' => now()],
            ['power' => '23706', 'date' => now()],
            ['power' => '29839', 'date' => now()],
            ['power' => '22595', 'date' => now()],
            ['power' => '25983', 'date' => now()],
            ['power' => '23445', 'date' => now()],
            ['power' => '20501', 'date' => now()],
            ['power' => '23900', 'date' => now()],
            ['power' => '18071', 'date' => now()],
            ['power' => '19733', 'date' => now()],
            ['power' => '24849', 'date' => now()],
            ['power' => '21689', 'date' => now()],
            ['power' => '27580', 'date' => now()],
            ['power' => '28624', 'date' => now()],
            ['power' => '22237', 'date' => now()],
            ['power' => '25951', 'date' => now()],
            ['power' => '29859', 'date' => now()],
            ['power' => '24334', 'date' => now()],
            ['power' => '23658', 'date' => now()],
            ['power' => '24117', 'date' => now()],
            ['power' => '23243', 'date' => now()],
            ['power' => '20293', 'date' => now()],
            ['power' => '26832', 'date' => now()],
            ['power' => '22029', 'date' => now()],
            ['power' => '28662', 'date' => now()],
            ['power' => '25838', 'date' => now()],
            ['power' => '18927', 'date' => now()],
            ['power' => '18785', 'date' => now()],
            ['power' => '21681', 'date' => now()],
            ['power' => '23952', 'date' => now()],
            ['power' => '22433', 'date' => now()],
            ['power' => '19353', 'date' => now()],
            ['power' => '24191', 'date' => now()],
            ['power' => '22035', 'date' => now()],
            ['power' => '20142', 'date' => now()],
            ['power' => '21204', 'date' => now()],
            ['power' => '21250', 'date' => now()],
            ['power' => '20817', 'date' => now()],
            ['power' => '21768', 'date' => now()],
            ['power' => '22206', 'date' => now()],
            ['power' => '21034', 'date' => now()],
            ['power' => '20744', 'date' => now()],
            ['power' => '21431', 'date' => now()],
            ['power' => '22655', 'date' => now()],
            ['power' => '23818', 'date' => now()],
            ['power' => '18911', 'date' => now()],
            ['power' => '23604', 'date' => now()],
            ['power' => '21964', 'date' => now()],
            ['power' => '28001', 'date' => now()],
            ['power' => '22010', 'date' => now()],
            ['power' => '21281', 'date' => now()],
            ['power' => '22446', 'date' => now()],
            ['power' => '23262', 'date' => now()],
            ['power' => '22126', 'date' => now()],
            ['power' => '21916', 'date' => now()],
            ['power' => '21117', 'date' => now()],
            ['power' => '21474', 'date' => now()],
            ['power' => '23871', 'date' => now()],
            ['power' => '17627', 'date' => now()],
            ['power' => '19082', 'date' => now()],
            ['power' => '21915', 'date' => now()],

        ]);
    }
}
